# Generated by Django 4.1.5 on 2023-01-11 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('admin_role', models.CharField(blank=True, max_length=150, null=True)),
                ('date_joined_sch', models.DateField()),
            ],
            options={
                'verbose_name': 'tutor',
                'verbose_name_plural': 'tutors',
            },
            bases=('users.customuser',),
            managers=[
                ('objects', users.models.MyUserManager()),
            ],
        ),
    ]
