# Generated by Django 4.1.5 on 2023-01-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('special_status', 'Can do all course CRUD')]},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'permissions': [('tutor_status', 'Can do all instructor CRUD')]},
        ),
    ]
